# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

#link_with 'Social Manager', 'Post Manager Extension'

target 'Social Manager' do
pod 'Alamofire'
pod 'AlamofireImage'
pod 'Google/Analytics'
end

target 'Development' do
pod 'Alamofire'
pod 'AlamofireImage'
pod 'Google/Analytics'
end

target 'Post Manager Extension' do
pod 'Alamofire'
pod 'AlamofireImage'
pod 'Google/Analytics'
end
